[package]
name = "noughts-and-crosses-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.0"
itertools = "0.10"
chrono = "0.4"
ahash = "0.7"
